version: '3'
services:
  minio-gw:
    image: minio/minio:RELEASE.2022-10-24T18-35-07Z
    command: gateway s3 ${BUCKET_HOST} --console-address ":9001"
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ACCESS_KEY: ${AWS_ACCESS_KEY_ID}
      MINIO_SECRET_KEY: ${AWS_SECRET_ACCESS_KEY}
    env_file:
      - .env
